version: '3.8'

services:
  web:
    image: ghcr.io/projekt-datascience/backend-audit:release
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    networks:
      - microservice-network
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-manager:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 8080:80
    networks:
      - microservice-network

networks:
  microservice-network: